[package]
name = "three_d"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { version = "0.15.2", features = ["dynamic_linking"] }
bevy_dylib = "0.15.2"
bevy_rapier3d = { version = "0.29.0", features = [
    "simd-stable",
    "debug-render-3d",
] }
