[package]
name = "three_d"
version = "0.1.0"
edition = "2021"

[dependencies]
bevy = { workspace = true, features = ["dynamic_linking"] }
bevy_rapier3d = { version = "0.29.0", features = [
    "simd-stable",
    "debug-render-3d",
] }
